login: &login
  encoding: utf8
  adapter: mysql
  username: root
  password: 
  # socket: /tmp/mysql.sock

development:
  database: mars
  <<: *login

test:
  database: mars_test
  <<: *login

production:
  database: mars
  <<: *login
